extends: stylelint-config-standard
ignoreFiles:
  - node_modules/**/*
  - packages/**/node_modules/**/*
  - build/**/*
plugins:
  - stylelint-scss
  - stylelint-order
rules:
  # Follow best practices
  font-family-name-quotes: always-where-recommended
  # https://stackoverflow.com/a/34383157/467582
  function-url-quotes: always
  # https://www.w3.org/TR/selectors/#attribute-selectors
  # http://stackoverflow.com/q/3851091
  selector-attribute-quotes: always
  # Double-quotes are our convention throughout our codebase within (S)CSS. They also reflect how
  # attribute strings are normally quoted within the DOM.
  string-quotes: double
  declaration-empty-line-before:
    - always
    - ignore:
      - after-comment
      - after-declaration
      - first-nested
      - inside-single-line-block
  order/order:
    -
      -
        type: at-rule
        hasBlock: false
      - custom-properties
      - declarations
    -
      unspecified: ignore
      disableFix: true
  order/properties-order:
    # Layout

    - clear
    - display
    - float
    - opacity
    - overflow
    - overflow-x
    - overflow-y
    - position
    - top
    - right
    - bottom
    - left
    - visibility
    - z-index

    - flex
    - flex-basis
    - flex-direction
    - flex-flow
    - flex-grow
    - flex-shrink
    - flex-wrap
    - align-content
    - align-items
    - align-self
    - justify-content
    - order

    # Box

    - box-sizing

    - border
    - border-top
    - border-right
    - border-bottom
    - border-left
    - border-width
    - border-top-width
    - border-right-width
    - border-bottom-width
    - border-left-width

    - border-style
    - border-top-style
    - border-right-style
    - border-bottom-style
    - border-left-style

    - border-radius
    - border-top-left-radius
    - border-top-right-radius
    - border-bottom-left-radius
    - border-bottom-right-radius

    - border-color
    - border-top-color
    - border-right-color
    - border-bottom-color
    - border-left-color

    - border-collapse
    - border-spacing

    - height
    - min-height
    - max-height

    - margin
    - margin-top
    - margin-right
    - margin-bottom
    - margin-left

    - padding
    - padding-top
    - padding-right
    - padding-bottom
    - padding-left

    - min-width
    - max-width
    - width

    - columns
    - column-count
    - column-gap
    - column-fill
    - column-rule
    - column-span
    - column-width

    - grid-gap
    - grid-template-columns

    - animation
    - animation-name
    - animation-timing-function

    - transform
    - transform-box
    - transform-origin
    - transform-style

    - transition
    - transition-delay
    - transition-duration
    - transition-property
    - transition-timing-function

    - outline
    - outline-color
    - outline-offset
    - outline-style
    - outline-width

    # Background

    - background
    - background-attachment
    - background-clip
    - background-color
    - background-image
    - background-repeat
    - background-position
    - background-size

    - fill

    # Text

    - color

    - font
    - font-family
    - font-size
    - font-smoothing
    - font-style
    - font-variant
    - font-weight

    - letter-spacing
    - line-height
    - list-style

    - text-align
    - text-decoration
    - text-indent
    - text-overflow
    - text-rendering
    - text-shadow
    - text-transform
    - text-wrap

    - white-space
    - word-spacing

    # Cursor

    - cursor
    - pointer-events
    - user-select

    # Other

    - appearance
    - box-shadow
    - caption-side
    - content
    - empty-cells
    - quotes
    - resize
    - speak
    - table-layout
    - vertical-align
    - will-change
  declaration-property-unit-whitelist:
    font-size:
      - "rem"
      - "px"
      - "%"
  # The following prefix rules are enabled since we use autoprefixer
  at-rule-no-vendor-prefix: true
  media-feature-name-no-vendor-prefix: true
  selector-no-vendor-prefix: true
  value-no-vendor-prefix: true
  # Control specificity
  max-nesting-depth: 3
  # Limit the amount of necessary compound selectors. Most should
  # just be 1 level selector.
  # Generic qualifying selectors (e.g. `[type="button"]`) can introduce another level.
  selector-max-compound-selectors: 4
  # For specificity: disallow IDs (0). Allow for complex combinations of classes, pseudo-classes,
  # attribute modifiers based on selector-max-compound-selectors, plus an addition for
  # pseudo-classes (4). Allow for pseudo-elements (1).
  selector-max-specificity: 0,4,1
  at-rule-no-unknown:
    - true
    - ignoreAtRules:
      - at-root
      - content
      - each
      - else
      - error
      - for
      - function
      - include
      - if
      - mixin
      - return
      - warn
      - while
  # Disallow "@extend" in scss.
  # selector, which can lead to ambiguous results.
  at-rule-blacklist:
    - extend
  # Extremely useful for typos, and anything emergent can be ignored by this rule
  property-no-unknown:
    - true
    - ignoreProperties:
        - contain
  selector-max-id: 0
  selector-no-qualifying-type: true
  # Turn off element selectors and force dev's to disable for specific cases
  # such as normalization or resets.
  selector-max-type:
    - 0
    - ignoreTypes:
        - /fieldset/
  # Styles for components should never need the universal selector.
  selector-max-universal: 0
  custom-media-pattern: ^[a-zA-z]+
  custom-property-pattern: ^[a-zA-z]+
  selector-class-pattern:
    - ^[a-zA-z]+
    - resolveNestedSelectors: true
  selector-id-pattern: ^[a-z]+
  # Names are more semantic than numbers
  font-weight-notation: named-where-possible
  # http://www.paulirish.com/2010/the-protocol-relative-url/
  function-url-no-scheme-relative: true
  comment-word-blacklist:
    -
      - /^TODO:/
      - /^FIXME:/
    - severity: warning
  number-leading-zero: always
  at-rule-empty-line-before:
    - always
    -
      except:
        - blockless-after-blockless
        - first-nested
      ignore:
        - after-comment
      ignoreAtRules:
        - else
  block-closing-brace-newline-after:
    - always
    - ignoreAtRules:
      - if
      - else

  # SCSS naming patterns, just like our CSS conventions above.
  # (note for $-vars we use a leading underscore for "private" variables)
  scss/dollar-variable-pattern:
    - ^_?tc-.+
    -
      ignore: local
  scss/at-function-pattern: ^_?tc-.+
  scss/at-mixin-pattern: ^_?tc-.+
  # Prevents unneeded nesting selectors
  scss/selector-no-redundant-nesting-selector: true
  # Since leading underscores are not needed, they can be omitted
  scss/at-import-no-partial-leading-underscore: true
  # Since mixins are explicit (`@include`) and parens are unnecessary for argumentless mixins, they
  # can be omitted.
  scss/at-else-closing-brace-newline-after: always-last-in-chain
  scss/at-else-closing-brace-space-after: always-intermediate
  scss/at-else-empty-line-before: never
  scss/at-if-closing-brace-newline-after: always-last-in-chain
  scss/at-if-closing-brace-space-after: always-intermediate
